# Generated by Django 3.0.5 on 2021-09-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210924_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
