# Generated by Django 3.0.5 on 2021-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210719_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='recipes.TagRecipe', to='recipes.Tag'),
        ),
    ]
