# Generated by Django 3.0.5 on 2021-10-29 10:09

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211026_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(max_length=64, validators=[recipes.validators.amount_validator], verbose_name='Количество'),
        ),
    ]
