# Generated by Django 3.0.5 on 2021-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210925_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='pictures', verbose_name='Изображение'),
        ),
    ]
