# Generated by Django 3.0.5 on 2021-10-29 10:10

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211029_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[recipes.validators.amount_validator], verbose_name='Количество'),
        ),
    ]
