# Generated by Django 3.0.5 on 2021-07-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210720_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_unit',
            new_name='unit',
        ),
    ]
