# Generated by Django 3.0.5 on 2021-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210926_2036'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_Favorite',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('recipe', 'author'), name='unique_favorite'),
        ),
    ]
