# Generated by Django 3.0.5 on 2021-08-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20210824_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
