# Generated by Django 3.0.5 on 2021-08-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_recipe_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
